spring:  mvc: # JSP 설정    view:      prefix: /WEB-INF/views/      suffix: .jsp

---
spring:
  datasource: # DB 접속 정보
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/as_service?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: user1
    password: test123

---
server:  port: 8088